### ISSUE TITLE
本地如何打包？

### ISSUE THREAD

**Issue by hellokaton** [ZhangJiupeng/AgentX#1]
我看到 https://github.com/ZhangJiupeng/AgentX/blob/master/agentx-server-1.2-install.sh#L57 这里有`agentx version`这种可执行命令，想请教是怎么打包的。

**Comment by ZhangJiupeng** [comment]
你指的是如何把 jar 包打包成服务吧，这个使用的是 [Java Service Wrapper](http://wrapper.tanukisoftware.com/doc/english/index.html)
