### ISSUE TITLE
UDP 中转好像有点问题

### ISSUE THREAD

**Issue by xiaohunsdt** [ZhangJiupeng/AgentX#2]
我吧项目部署到国内服务器上，测试了TCP，是稳定的，但是当我测试用代理玩王者荣耀的时候，UDP中转好像有点问题

**Comment by ZhangJiupeng** [comment]
这版目前还不支持UDP转发

**Comment by xiaohunsdt** [comment]
大神打算什么时候出新版，并且加上这个功能？我目前正在学习中
