### ISSUE TITLE
关于Shadowsocks被特征识别

### ISSUE THREAD

**Issue by ZhangJiupeng** [ZhangJiupeng/AgentX#3]
近期SS已被GFW针对，有翻墙需求的同学可以考虑使用FakedHttp协议配置代理；

作者目前正在开发新协议，有关更新将于近期发布。

传送门：
讨论：<https://github.com/shadowsocks/shadowsocks/issues/988>
论文：<https://sci-hub.cc/http://ieeexplore.ieee.org/document/8048116/>

**Comment by ShinChven** [comment]
表示关注

**Comment by nanyang24** [comment]
关注中

**Comment by fankeke** [comment]
关注。

**Comment by timeliar** [comment]
他这个识别是在运营商当中间人抓数据吗

**Comment by custa** [comment]
端口被封，换个端口继续用，不知能扛多久。

**Comment by zhe13** [comment]
趁机学习一波

**Comment by work-chausat** [comment]
严重关注！！
